name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with OTP ${{matrix.otp}} and Elixir ${{matrix.elixir}}

    strategy:
      matrix:
        include:
        - otp: 25.2
          elixir: 1.15.2

        - otp: 26.2
          elixir: 1.16.2

        - otp: 27.2
          elixir: 1.17.2

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-

    - name: Install dependencies
      run: mix deps.get --only test

    - name: Run tests
      run: mix test
